### ISSUE TITLE
readme says executionbackup-rust instead of executionbackup

### ISSUE THREAD

**Issue by newearthmartin** [TennisBowling/executionbackup#21]
<img width="775" alt="Screenshot 2023-04-10 at 23 39 15" src="https://user-images.githubusercontent.com/1507266/231041644-1e0f4d79-6d5c-47f5-b6e6-4fce16a8ac3a.png">

**Comment by newearthmartin** [comment]
Also the executable is still called `executionbackup-rust` instead of `executionbackup`

**Comment by carloscip** [comment]
I noticed the same, but also If building [https://github.com/TennisBowling/executionbackup.git](https://github.com/TennisBowling/executionbackup.git) the version of the binaries (if calling `executionbackup-rust -V` is 1.0.2 wich is really outdated).
I think there is something wrong, it could be just an issue of the displayed version, or something else. But even downloading latest binaries "v1.0.6" when running it says "Starting executionbackup version 1.0.2"

**Comment by newearthmartin** [comment]
I created a PR for this

https://github.com/TennisBowling/executionbackup/pull/22

**Comment by newearthmartin** [comment]
@carloscip this is because there used to be 2 different repos: executionbackup and executionbackup-rust and the author merged them into executionbackup

**Comment by TennisBowling** [comment]
Sorry I didn't see this earlier, I'll get the names down!

**Comment by newearthmartin** [comment]
Hey @TennisBowling apparently there are a couple references to `executionbackup-rust` left:

https://github.com/search?q=repo%3ATennisBowling%2Fexecutionbackup%20executionbackup-rust&type=code

Can you fix them?
