### ISSUE TITLE
Releases version say to be all v1.0.2

### ISSUE THREAD

**Issue by carloscip** [TennisBowling/executionbackup#23]
I tried building the binary from source but I kept on getting v1.0.2 when querying the `--version` flag. I even tried downloading the latests 2 releases, and same occurs there, it is reporting v1.0.2. Is this just a version display error? or is it there another issue? Also when running the program I kept on getting timeout errors (which I did't use to get with version v1.0.4 that was the last one I used)

**Comment by newearthmartin** [comment]
That's fixed in my PR https://github.com/TennisBowling/executionbackup/pull/22

**Comment by carloscip** [comment]
> That's fixed in my PR #22

Yeah you are right! Let's wait for it to be merged then. Thanks!
