### ISSUE TITLE
Effectiveness decrease when more nodes added

### ISSUE THREAD

**Issue by carloscip** [TennisBowling/executionbackup#27]
Hi, I've noticed that when adding more execution engine nodes to the executionbackup script, it tends to affect on effectiveness value shown on beaconcha.in and also makes it lose more attestations. So far my tests concluded that 2 is the sweet spot. Do you have any idea? Thanks

**Comment by TennisBowling** [comment]
It might be because some nodes are slower than others, which causes more waiting on EB. how many nodes were you using and are all on fast/decently fast hardware? you should try now as the algorithm for that has been changed.

**Comment by TennisBowling** [comment]
you can also use `--node-timings` to see these times @carloscip
